# Generated by Django 2.2 on 2019-07-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'pessoa 2', 'verbose_name_plural': 'pessoas 2'},
        ),
    ]
