# Generated by Django 2.2 on 2019-11-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_customer_invoice_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kind',
            field=models.TextField(choices=[('0', 'RG'), ('1', 'CPF'), ('2', 'CNH'), ('3', 'Comprovante Endereço')], default=2, max_length=1, verbose_name='Tipo Documento'),
            preserve_default=False,
        ),
    ]
