# Generated by Django 2.2 on 2019-07-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_contacts', to='person.Person', verbose_name='Pessoa'),
        ),
        migrations.CreateModel(
            name='FilesDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(choices=[('0', 'Telefone Fixo'), ('1', 'Celular 1'), ('2', 'Celular 2'), ('3', 'Celular 3'), ('4', 'E-Mail'), ('5', 'Telefone Trabalho')], max_length=1, verbose_name='Tipo Documento')),
                ('file_document', models.FileField(upload_to='documents/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_documents', to='person.Person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ('kind',),
            },
        ),
    ]
