# Generated by Django 2.2 on 2019-07-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20190708_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='E-Mail'),
        ),
    ]
